name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Cleaning Code
      run: |
        find . -name '*.py' -exec autopep8 --in-place '{}' \;
        find . -name '*.py' -exec black '{}' \;
    - name: Comitting Cleaned Code
      uses: EndBug/add-and-commit@v7
      with:     
        default_author: github_actions
        committer_name: GitHub Actions
        committer_email: actions@github.com
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
